name: Artifacts Publish

on:
  workflow_dispatch:
    inputs:
      message:
        description: 'Message for manually triggering'
        required: false
        default: 'Triggered for inji-vci-client Updates'
        type: string
      publication_type:
        description: 'Select artifact type to publish'
        required: true
        default: both
        type: choice
        options:
          - aar
          - jar
          - both

jobs:
  maven-publish:
    uses: Prafulrakhade/kattu/.github/workflows/maven-publish-android-download.yaml@master-conditional-checks
    with:
      SERVICE_LOCATION: 'kotlin'
      ANDROID_SERVICE_LOCATION: 'vci-client'
      JAVA_VERSION: 21
      LICENSE_NAME: 'MPL-2.0'
      PUBLICATION_TYPE: ${{ inputs.publication_type }}
    secrets:
      OSSRH_USER: ${{ secrets.OSSRH_USER }}
      OSSRH_URL: ${{secrets.OSSRH_GRADLE_URL }}
      OSSRH_SECRET: ${{ secrets.OSSRH_SECRET }}
      OSSRH_TOKEN: ${{ secrets.OSSRH_TOKEN }}
      GPG_SECRET: ${{ secrets.GPG_SECRET }}
      SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_INJI_TEAM }}

