name: Push trigger for inji-vci-client

on:
  push:
    branches:
    - main
    - develop
    - qa-develop
    - 'release-**'
  pull_request:
    types: [opened, reopened, synchronize]
    branches:
    - main
    - develop
    - qa-develop
    - 'release-**'

jobs:
  build-kotlin:
    runs-on: ubuntu-latest
    steps:
      - name: Set up JDK 21
        uses: actions/setup-java@v3
        with:
          distribution: adopt
          java-version: 21
          server-id: ossrh
          settings-path: ${{ github.workspace }}

      - name: Cache Gradle packages
        uses: actions/cache@v3.3.1
        with:
          path: |
            ~/.gradle/caches
            ~/.gradle/wrapper
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle') }}
          restore-keys: ${{ runner.os }}-gradle-

      - uses: actions/checkout@v3.1.0
      - name: Run kotlin tests
        run: |
          cd kotlin
          ./gradlew test

      - uses: 8398a7/action-slack@v3
        with:
          status: ${{ job.status }}
          fields: repo,message,author,commit,workflow,job 
        env:
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_INJI_TEAM }}
        if: "${{ github.event_name != 'pull_request' && failure() }}"

  build-js:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3.1.0
      - name: Run js tests
        run: |
          cd js
          npm ci
          npm test

      - uses: 8398a7/action-slack@v3
        with:
          status: ${{ job.status }}
          fields: repo,message,author,commit,workflow,job 
        env:
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_INJI_TEAM }}
        if: "${{ github.event_name != 'pull_request' && failure() }}"